### PR TITLE
Added Makefile

### PR DESCRIPTION
**Pull request by libre-hackerman**
Hi! I replaced the build script with a Makefile that allows to easily clean, recompile (with debug mode), install and uninstall fakesteak.

### CODE REVIEW

**Comment by domsson** [comment]
Hey hackerman, thank you for your contribution! There are two reasons I used a simple bash script instead of a makefile:

- I'm somewhat of a minimalist and it is only one line after all
- I have never used makefiles and therefore don't know their syntax / rules

Now, I understand that `make` is pretty much the de facto standard for C project compilation in UNIX, so I guess it is about time I finally wrap my head around it. Here is where I'm in a little bit of a dilemma: I've just spend about an hour (that's about all I had after work) today on reading up on Makefiles and still only understand part of what's going on. Therefore, I can't attest to the quality of the Makefile and would not be able to fix any potential issues with it. I'm not quite comfortable with that.

On the other hand, I really appreciate your contribution and assume it might make your plans of potentially integrating this with Gentoo easier. I'd therefore really like to pull this in before my slow brain finally manages to understand every detail of it. So, here is a suggestion: could we simplify this as much as possible, given the assumption that fakesteak will most likely never grow past one single source file? That way, I could more easily wrap my head around it and pull it in with confidence. With my limited knowledge from the quick research, maybe something like this would be sufficient?

	CFLAGS := -Wall -O3
	LDLIBS := -lm
	PREFIX := /usr/local/
	NAME := fakesteak
	
	.PHONY = release debug install uninstall
	
	release:
		$(CC) $(CFLAGS) -o bin/$(NAME) src/$(NAME).c $(LDLIBS)
	
	debug: CFLAGS := -Wall -g
	debug: release
	
	install:
		cp bin/$(NAME) $(PREFIX)/bin
		chmod +x $(PREFIX)/bin/$(NAME)
	
	uninstall:
		rm $(PREFIX)/bin/$(NAME)        

Also, a couple quick questions regarding your file:

- I see you used `cc` instead of `gcc`; any particular reason? I see that on my system `cc` is a symlink to `gcc`.
- Is installing to `/usr/local/bin` standard? I assume this means make would need to be ran with su/sudo?
- What's the reasoning behind `=` for variables sometimes, `+=` other times?
- Is just adding `-g` to `-Wall -O3` enough? Wouldn't we also need to remove `-O3` or does `-g` turn off optimization anyway?
- Can the `Makefile` also be called `makefile`?

Sorry if you're smacking your head right now. :)

**Comment by libre-hackerman** [comment]
Hi! I like your simplified Makefile, but I would make some changes. I would rename your `release` target to `all`, which is the default target called when running `make` without anything else. I also would still add the `clean` target since its a widely used one too. We can simplify it by just doing an `rm -f` on the binary. And by convention, .PHONY goes at the end of the Makefile. I also would change some `:=` with `+=`.

Answering the other questions:
- `cc` will refer to the default C compiler installed on the system, which usually is GCC but could be Clang or others, making the Makefile more portable.
- Yes, is the default place where Makefiles install binaries by convention (indeed needing root permissions). This is to differentiate from the binaries installed by your package manager in `/usr/bin`. This can be changed by passing a different PREFIX variable when calling `make`.
- In the variables I use `=` I just want to set a value. In the ones I use '+=' I want to add to what might be already set from outside. For example, Portage (the package manager of Gentoo) will add the CFLAGS set in its config to the ones set in the Makefile.
- Didn't know the answer to this one, but I just checked and just adding `-g` seems to work fine adding debugging symbols.
- Yes, although most of the Makefiles I've encountered use the `Makefile` form.

Note that I also started with Makefiles somewhat recently so I'm not an expert on this either.

**Comment by libre-hackerman** [comment]
So apart from the changes I mentioned to the Makefile you proposed, I added some `mkdir -p` to ensure some directories exists before acting on them, and I added the binary as dependency to the `install` target to ensure that the binary exists before installing. And because of this, I set the `all` target also to the binary one so Make knows how to create it.

Please let me know if you are OK with this modifications :)

**Comment by domsson** [comment]
Thank you very much for answering all my questions and addressing my concerns. I feel like I now understand what is going on in the file. More importantly, I've gained a rough understanding of makefiles in general. Very much appreciated. Merged. :)

**Pull request merged**
